// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_path_ from "./routes/api/[...path].tsx";
import * as $api_auth from "./routes/api/auth.ts";
import * as $api_calendar from "./routes/api/calendar.ts";
import * as $api_shift from "./routes/api/shift.ts";
import * as $detail_name_ from "./routes/detail/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $setting from "./routes/setting.tsx";
import * as $CalendarSetting from "./islands/CalendarSetting.tsx";
import * as $Detail from "./islands/Detail.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $List from "./islands/List.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $Profile from "./islands/Profile.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/[...path].tsx": $api_path_,
    "./routes/api/auth.ts": $api_auth,
    "./routes/api/calendar.ts": $api_calendar,
    "./routes/api/shift.ts": $api_shift,
    "./routes/detail/[name].tsx": $detail_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/profile.tsx": $profile,
    "./routes/setting.tsx": $setting,
  },
  islands: {
    "./islands/CalendarSetting.tsx": $CalendarSetting,
    "./islands/Detail.tsx": $Detail,
    "./islands/Header.tsx": $Header,
    "./islands/List.tsx": $List,
    "./islands/Login.tsx": $Login,
    "./islands/Profile.tsx": $Profile,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
